Blog/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

Blog/mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from blog import views
from django.contrib.sitemaps.views import sitemap
from blog import sitemaps
from blog.sitemaps import PostSitemap

app_name = 'blog'

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

Blog/blog/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from taggit.managers import TaggableManager

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

class Meta:
    ordering = ('-publish',)
    def __str__(self):
        return self.title

class PostAdmin(admin.ModelAdmin):
    list_display = ('title', 'slug', 'author', 'publish', 'status')


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)



class Meta:
    ordering = ('created',)
def __str__(self):
    return f'Comment by {self.name} on {self.post}'

Blog/blog/forms.py
from socket import fromshare
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')  

Blog/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm
from django.core.mail import send_mail
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
from taggit.models import Tag
from django.db.models import Count
# Create your views here.



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = CommentForm(data=request.POST)
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
        else:
            comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True) 
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('same_tags','publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form, 'similar_posts': similar_posts})

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    posts = Post.published.order_by()
    object_list = Post.published.order_by()
    paginator = Paginator(object_list, 2) # 2 posts in each page
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        page_obj = paginator.get_page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        page_obj= paginator.get_page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page_obj': page_obj, 'posts': posts, 'tag': tag})
    

class PostListView(ListView):
    queryset = Post.published.order_by()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/post/list.html'



def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
    # Form was submitted
        form = EmailPostForm(request.POST)
    
        if form.is_valid():
        # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'danielidhosa98@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

Blog/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %} 

<!DOCTYPE html>
   
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/blog.css" %}" rel="stylesheet">
    </head>
    
    <body>
        
        
       

        <div class="w3-sidebar w3-bar-block" style="display:none" id="mySidebar">
            <button onclick="w3_close()" class="w3-bar-item w3-button w3-large">Close &times;</button>
            <a href="http://127.0.0.1:8000/blog/" class="w3-bar-item w3-button">Home</a>
            <a href="http://127.0.0.1:8000/blog/2022/9/26/who-is-it/" class="w3-bar-item w3-button">Who is Django Reinhardt?>
            <a href="http://127.0.0.1:8000/blog/2022/9/26/who-is-it2/" class="w3-bar-item w3-button">What is Ripple?</a>
            <a href="http://127.0.0.1:8000/blog/2022/9/26/who-is-it3/" class="w3-bar-item w3-button">What is a Manga?</a>
            <a href="http://127.0.0.1:8000/blog/2022/10/4/This_is_a_post_formatted_with_markdown1/" class="w3-bar-item w3-button">This is a post formatted with markdown</a>

        </div>
        <div style="margin-left:25%"></div>

        <p>
            <a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a>
        </p>
         
        
        
        
        </div>
        <div class="w3-teal">
            <button class="w3-button w3-teal w3-xlarge" onclick="w3_open()">☰</button>
           
        </div>
        <div class="w3-container">
            <!--In this example, the sidebar is hidden (style="display:none")
                It is shown when you click on the menu icon in the top left corner
                When it is opened, it hides all the page content (style.width="100%").
            -->
        </div>
            
        <script>
            function w3_open() {
              document.getElementById("mySidebar").style.width = "100%";
              document.getElementById("mySidebar").style.display = "block";
            }
            
            function w3_close() {
              document.getElementById("mySidebar").style.display = "none";
            }
        </script>
                 

        <div id="content">
            
            {% block content %}
            
            {% endblock %}
            
        </div>
        
        
        
    </body>
</html>

Blog/blog/templates/blog/pagination.html
{% for contact in page_obj %}
    {# Each "contact" is a Contact model object. #}
    {{ contact.full_name|upper }}<br>
    ...
{% endfor %}

<div class="pagination">
    <span class="step-links">
        <ol>
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page.previous_page_number }}">Previous</a>
            {% endif %}
            
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </ol>
        
    </span>
</div>

Blog/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}
    
    {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}

    
    
    {% include "blog/pagination.html" with page=page_obj %}
    
{% endblock %}

Blog/blog/templates/blog/post/latest_posts.html

<html>

    <ul>
        {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% endfor %}
    </ul>

</html>

Blog/blog/templates/blog/post/list.html

<html>


    {% extends "blog/base.html" %}

    {% load blog_tags %}
    {% block title %}My Blog {% endblock %}
    
  
    
    {% block content %}
        
        <div id="sidebar">
            <h1>My blog</h1>
            <p>This is my blog. I've written {% total_posts %} posts so far.</p>
            <h3>Latest posts</h3>
            {% show_latest_posts 3 %}
            <h3>Most commented posts</h3>
            {% get_most_commented_posts as most_commented_posts %}
            <ul>
                {% for post in most_commented_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
            
        {% if tag %}
            <p class="tags">
                Tags:
                    {% for tag in post.tags.all %}
                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
            </p>
        {% endif %}
        {% for post in posts %}
            <h2>
                <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
            </h2>
            <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>
            <p class="date">
                Published {{ post.publish }} by {{ post.author }}
            </p>
            {{ post.body|markdown|truncatewords_html:30 }}    
        {% endfor %}
        {% include "blog/pagination.html" with page=page_obj %}
    {% endblock %}

</html>




Blog/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}